{% set name = "Orange3-Text" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d260dacc174cf71f89784b1560cbef6a36c5e115cf45d349ea9494d582a8b50b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy
    - nltk >=3.0.5
    - scikit-learn
    - numpy
    - python-dateutil <3.0.0
    - gensim >=0.12.3,!=4.0.0,!=4.0.1
    - setuptools-git
    - orange3 >=3.28.0
    - tweepy
    - beautifulsoup4
    - simhash >=1.11.0
    - wikipedia
    - pdfminer3k >=1.3.1
    - odfpy >=1.3.5
    - docx2txt >=0.6
    - lxml
    - biopython
    - ufal.udpipe >=1.2.0.3
    - orange-widget-base >=4.12.0
    - yake
    - conllu
    - lemmagen3

test:
  commands:
    # make sure all required dependencies are present
    - python -c "import pkg_resources; pkg_resources.require('Orange3-Text')"
  imports:
    - orangecontrib.text

about:
  home: https://github.com/biolab/orange3-text
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE
  summary: Orange3 add-on for analyzing textual data.

  description: |
    Orange add-on for text mining. It provides access to publicly available
    data, like NY Times, Twitter and PubMed. Further, it provides tools for
    preprocessing, constructing vector spaces (like bag-of-words and topic
    modeling) and visualizations like word cloud and geo map. All features
    can be combined with powerful data mining techniques from the Orange
    data mining framework.

  doc_url: http://orange3-text.readthedocs.io
  dev_url: https://github.com/biolab/orange3-text

extra:
  recipe-maintainers:
    - nikicc
    - astaric
    - ajdapretnar
    - primozgodec
