{% set name = "Orange3-Text" %}
{% set version = "0.2.5" %}
{% set sha256 = "bd1aa2ecebecfaa6ef03c136fb650f2de1bb7dcaa2fa24e14fd1e83e53b72780" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - biopython
    - scipy
    - nltk            >=3.0.5
    - scikit-learn
    - numpy
    - gensim          >=0.12.3
    - setuptools-git
    - orange3         >=3.4.3
    - anyqt
    - beautifulsoup4
    - validate_email
    - tweepy
    - simhash
    - wikipedia
    - typing
    - pdfminer3k      >=1.3.1
    - odfpy           >=1.3.5
    - docx2txt        >=0.6
    - lxml


test:
  commands:
    # make sure all required dependencies are present
    - python -c "import pkg_resources; pkg_resources.require('Orange3-Text')"
  imports:
    - orangecontrib.text

about:
  home: https://github.com/biolab/orange3-text
  license: AGPLv3
  license_family: AGPL
  license_file: LICENSE
  summary: 'Orange3 add-on for analyzing textual data.'

  description: |
    Orange add-on for text mining. It provides access to publicly available
    data, like NY Times, Twitter and PubMed. Further, it provides tools for
    preprocessing, constructing vector spaces (like bag-of-words and topic
    modeling) and visualizations like word cloud and geo map. All features
    can be combined with powerful data mining techniques from the Orange
    data mining framework.

  doc_url: http://orange3-text.readthedocs.io
  dev_url: https://github.com/biolab/orange3-text

extra:
  recipe-maintainers:
    - nikicc
    - kernc
    - astaric
