appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: o0lPuhtOOso+meTlsObQmAePIUDf4WYhyeJztAhvfur9HjwiwTpd1nKbU7m+MEeBnC5SHSpLD6z7sqhmeckurFZgDnQswJFGTDGGU7x+kqaUcm1roV77cLtHVKcclTxdiSdgNI7OsgjkxhWGa3sxkRMsCnmEL6TcCwRyUb+wFkB3/tuL0gHZ5DQGNTZSjDem0k8ebcxmjOvitShSzD8JRzOx6v6UjsqtgMB0yV3ccfrMArzGC8lyKLD0eXh6eUDAZtYaaeaN4pUHvI+5QoqbdhE74qaEN/Zcwr37lSgDltSYpnDgWy1QU+Y9h8A+LASEZSoPvgbu8pHoh3pblVkkTduFBKhrlHqz8jcEYqrI6xXrdoIaEuePOlnWSHgJVCIxCCgy85VbCSinj43xI3A8onU/S/7UftAkFvLijb16ObY00c0mKWLzm/nPZyP0M7hU6HK4oMED339vlMhCD8g+JFJqhE0cWPpJequAbdznSRWd5U6MCNb1M/HtPlYg+ri+id0DYBFxiqlyKvsfzyiy20xDjKWQKHEevJ+KHQYxDVZ8O4KjuKM6ST5XsbN0D8G0+tpqcLCmpd//fcS8WNwI/F7SPGF10HwhbHnn0L08qVjX8vgvCfHk4JBp6Mgeg7rCpN9Kp7ckE0Vt5TWVsy5bX4SEy9Faxc0EgQt1lkFOkbo=}
